version: '3.8'

services:
  h2-ai:
    image: oscarfonts/h2
    container_name: h2-ai-database
    ports:
      - "1522:1521"
      - "82:81" 
    volumes:
      - h2-ai-data:/opt/h2-data
    environment:
      H2_OPTIONS: "-ifNotExists"
      H2_USER: aiuser
      H2_PASSWORD: aipassword

volumes:
  h2-ai-data:
    driver: local
