version: '3.8'

services:
  cryptoSageApp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ZONDA_API_KEY=${ZONDA_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
