version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      H2_OPTIONS: "-ifNotExists"
      H2_USER: user
      H2_PASSWORD: password

volumes:
  h2-data:
    driver: local
