name: AI Service - Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "agent-ai/**"
  workflow_dispatch:

jobs:
  build-and-push-agent-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image for AI Service
        run: docker build -f ./agent-ai/docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/agent-ai:latest ./agent-ai

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/agent-ai:latest

  deploy-agent-ai:
    needs: build-and-push-agent-ai
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AI Service to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          port: 22
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            set -e
            docker pull ${{ secrets.DOCKER_USERNAME }}/agent-ai:latest
            docker stop agent-ai || true
            docker rm agent-ai || true
            docker run -d --restart always --name agent-ai \
              -e DB_AI_URL=${{ secrets.DB_AI_URL }} \
              -e DB_AI_USERNAME=${{ secrets.DB_AI_USERNAME }} \
              -e DB_AI_PASSWORD=${{ secrets.DB_AI_PASSWORD }} \
              -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/agent-ai:latest
