
server:
  servlet:
    context-path: /api

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: maticzworrior@gmail.com
    password: ${SMTP_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database: h2
  datasource:
    url: jdbc:h2:tcp://localhost:1521/default
    username: user
    password: password
    driver-class-name: org.h2.Driver

app:
  notification:
    email:
      recipients:
        - mateuszdeptulski@gmail.com