server:
  servlet:
    context-path: /api

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: maticzworrior@gmail.com
    password: ${SMTP_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database: h2
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: never
      data-locations: classpath:db/create-crypto-pairs-1.sql
      platform: h2


logging:
  file:
    path: /home/mateusz/apps/app-logs/crypto-app
    name: crypto-app.log
  level:
    pl.kathelan.cryptosageapp.zonda: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

scheduler:
  enabled: true

app:
  notification:
    email:
      recipients:
        - mateuszdeptulski@gmail.com


